// --- Size Configuration ---
export const sizeConfig = {
  sm: {
    container: 'rounded-xl p-3',
    header: 'text-xs mb-3 gap-1.5',
    icon: 14,
    display: 'text-lg py-1.5 px-2 rounded-lg',
    colon: 'text-lg mx-0.5',
    scroll: 'h-[100px]',
    itemHeight: 'h-[28px]',
    itemFont: 'text-xs',
    itemSelectedFont: 'text-sm',
    ampm: 'px-2 py-0.5 text-[10px]',
    gradient: 'h-[35px]',
    indicator: 'h-[28px]',
    label: 'text-[10px]',
    gap: 4,
  },
  md: {
    container: 'rounded-2xl p-5',
    header: 'text-sm mb-4 gap-2',
    icon: 16,
    display: 'text-2xl py-2 px-3 rounded-xl min-w-[60px]',
    colon: 'text-xl mx-1',
    scroll: 'h-[150px]',
    itemHeight: 'h-[32px]',
    itemFont: 'text-sm',
    itemSelectedFont: 'text-lg',
    ampm: 'px-2.5 py-1 text-[11px]',
    gradient: 'h-[42px]',
    indicator: 'h-[32px]',
    label: 'text-[11px]',
    gap: 6,
  },
  lg: {
    container: 'rounded-3xl p-6',
    header: 'text-base mb-5 gap-2',
    icon: 18,
    display: 'text-3xl py-2 px-4 rounded-xl min-w-[80px]',
    colon: 'text-2xl mx-1.5',
    scroll: 'h-[180px]',
    itemHeight: 'h-[36px]',
    itemFont: 'text-base',
    itemSelectedFont: 'text-xl',
    ampm: 'px-3 py-1 text-xs',
    gradient: 'h-[50px]',
    indicator: 'h-[36px]',
    label: 'text-xs',
    gap: 8,
  },
};
